
import { Category, Product, Vendor } from '../src/types';

export const NIGERIA_LOCATIONS: Record<string, string[]> = {
  "FCT": ["Abaji", "Bwari", "Gwagwalada", "Kuje", "Kwali", "Municipal Area Council"],
  "Abia": ["Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala Ngwa North", "Isiala Ngwa South", "Isuikwuato", "Obi Ngwa", "Ohafia", "Osisioma", "Ugwunagbo", "Ukwa East", "Ukwa West", "Umuahia North", "Umuahia South", "Umu Nneochi"],
  "Lagos": ["Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa", "Badagry", "Epe", "Eti Osa", "Ibeju-Lekki", "Ifako-Ijaiye", "Ikeja", "Ikorodu", "Kosofe", "Lagos Island", "Lagos Mainland", "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere"],
  "Kano": ["Ajingi", "Albasu", "Bagwai", "Bebeji", "Bichi", "Bunkure", "Dala", "Dambatta", "Dawakin Kudu", "Dawakin Tofa", "Doguwa", "Fagge", "Gabasawa", "Garko", "Garun Mallam", "Gaya", "Gezawa", "Gwale", "Gwarzo", "Kabo", "Kano Municipal", "Karaye", "Kibiya", "Kiru", "Kumbotso", "Kunchi", "Kura", "Madobi", "Makoda", "Minjibir", "Nasarawa", "Rano", "Rimin Gado", "Rogo", "Shanono", "Sumaila", "Takai", "Tarauni", "Tofa", "Tsanyawa", "Tudun Wada", "Ungogo", "Warawa", "Wudil"],
  "Rivers": ["Abua/Odual", "Ahoada East", "Ahoada West", "Akuku-Toru", "Andoni", "Asari-Toru", "Bonny", "Degema", "Eleme", "Emuoha", "Etche", "Gokana", "Ikwerre", "Khana", "Obio/Akpor", "Ogba/Egbema/Ndoni", "Ogu/Bolo", "Okrika", "Omuma", "Opobo/Nkoro", "Oyigbo", "Port Harcourt", "Tai"]
  // Add more states as needed
};

export const VENDORS: Vendor[] = [
  {
    id: 'v1',
    name: 'Green Valley Organics',
    location: 'Kuje, FCT',
    rating: 4.9,
    image: 'https://picsum.photos/id/102/400/400',
    description: 'Certified organic family farm specializing in heirlooms.',
  },
  {
    id: 'v2',
    name: 'Sunrise Dairy Farm',
    location: 'Gwagwalada, FCT',
    rating: 4.8,
    image: 'https://picsum.photos/id/108/400/400',
    description: 'Grass-fed dairy and free-range eggs.',
  },
  {
    id: 'v3',
    name: 'Orchard Hill',
    location: 'Bwari, FCT',
    rating: 4.7,
    image: 'https://picsum.photos/id/292/400/400',
    description: 'Seasonal fruits, ciders, and homemade jams.',
  },
];

const MOCK_REVIEWS = [
  { id: 'r1', userName: 'Sarah M.', rating: 5, comment: 'Absolutely delicious and fresh!', date: '2023-10-15' },
  { id: 'r2', userName: 'John D.', rating: 4, comment: 'Great quality but a bit pricey.', date: '2023-10-12' },
  { id: 'r3', userName: 'Emily R.', rating: 5, comment: 'Best I have ever tasted. Will buy again.', date: '2023-09-28' },
];

// Prices converted roughly to Naira for realism
export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Organic Kale Bunch',
    price: 1500,
    unit: 'bunch',
    category: Category.VEGETABLES,
    image: 'https://picsum.photos/id/1080/600/600',
    vendorId: 'v1',
    description: 'Fresh, crisp organic kale harvested daily.',
    rating: 4.8,
    reviews: 124,
    isSeasonal: true,
    reviewsList: MOCK_REVIEWS,
    stock: 50,
    status: 'Active'
  },
  {
    id: 'p2',
    name: 'Honeycrisp Apples',
    price: 3500,
    unit: 'kg',
    category: Category.FRUITS,
    image: 'https://picsum.photos/id/102/600/600',
    vendorId: 'v3',
    description: 'Sweet and crisp apples perfect for snacking.',
    rating: 4.9,
    reviews: 89,
    isSeasonal: true,
    reviewsList: MOCK_REVIEWS,
    stock: 40,
    status: 'Active'
  },
  {
    id: 'p3',
    name: 'Free-Range Eggs',
    price: 4500,
    unit: 'crate',
    category: Category.DAIRY,
    image: 'https://picsum.photos/id/400/600/600',
    vendorId: 'v2',
    description: 'Large brown eggs from happy, pasture-raised hens.',
    rating: 5.0,
    reviews: 210,
    reviewsList: MOCK_REVIEWS,
    stock: 30,
    status: 'Active'
  },
  {
    id: 'p4',
    name: 'Artisan Sourdough',
    price: 2500,
    unit: 'loaf',
    category: Category.PANTRY,
    image: 'https://picsum.photos/id/999/600/600',
    vendorId: 'v1',
    description: 'Slow-fermented sourdough bread with a crispy crust.',
    rating: 4.7,
    reviews: 56,
    reviewsList: MOCK_REVIEWS,
    stock: 15,
    status: 'Active'
  },
  {
    id: 'p5',
    name: 'Raw Honey',
    price: 8000,
    unit: 'jar',
    category: Category.PANTRY,
    image: 'https://picsum.photos/id/312/600/600',
    vendorId: 'v3',
    description: 'Unfiltered raw honey from local wildflowers.',
    rating: 4.9,
    reviews: 150,
    reviewsList: MOCK_REVIEWS,
    stock: 45,
    status: 'Active'
  },
  {
    id: 'p6',
    name: 'Heirloom Tomatoes',
    price: 2000,
    unit: 'kg',
    category: Category.VEGETABLES,
    image: 'https://picsum.photos/id/800/600/600',
    vendorId: 'v1',
    description: 'Juicy, colorful heirloom tomatoes rich in flavor.',
    rating: 4.6,
    reviews: 78,
    isSeasonal: true,
    reviewsList: MOCK_REVIEWS,
    stock: 25,
    status: 'Active'
  },
  {
    id: 'p7',
    name: 'Grass-Fed Ground Beef',
    price: 5500,
    unit: 'kg',
    category: Category.MEAT,
    image: 'https://picsum.photos/id/1070/600/600',
    vendorId: 'v2',
    description: 'Lean, flavorful ground beef from pasture-raised cattle.',
    rating: 4.8,
    reviews: 92,
    reviewsList: MOCK_REVIEWS,
    stock: 20,
    status: 'Active'
  },
  {
    id: 'p8',
    name: 'Fresh Strawberries',
    price: 4000,
    unit: 'basket',
    category: Category.FRUITS,
    image: 'https://picsum.photos/id/429/600/600',
    vendorId: 'v3',
    description: 'Sweet, ruby-red strawberries picked at peak ripeness.',
    rating: 4.9,
    reviews: 300,
    isSeasonal: true,
    reviewsList: MOCK_REVIEWS,
    stock: 35,
    status: 'Active'
  },
  {
    id: 'p9',
    name: 'Russet Potatoes',
    price: 3000,
    unit: 'kg',
    category: Category.TUBERS,
    image: 'https://picsum.photos/id/292/600/600',
    vendorId: 'v1',
    description: 'Earthy russet potatoes, great for baking.',
    rating: 4.5,
    reviews: 40,
    reviewsList: MOCK_REVIEWS,
    stock: 100,
    status: 'Active'
  },
  {
    id: 'p10',
    name: 'Almonds',
    price: 6500,
    unit: 'pack',
    category: Category.NUTS,
    image: 'https://picsum.photos/id/305/600/600',
    vendorId: 'v3',
    description: 'Raw, unsalted almonds.',
    rating: 4.9,
    reviews: 120,
    reviewsList: MOCK_REVIEWS,
    stock: 50,
    status: 'Active'
  },
  {
    id: 'p11',
    name: 'Quinoa',
    price: 4500,
    unit: 'pack',
    category: Category.GRAINS,
    image: 'https://picsum.photos/id/22/600/600',
    vendorId: 'v1',
    description: 'Organic white quinoa.',
    rating: 4.6,
    reviews: 30,
    reviewsList: MOCK_REVIEWS,
    stock: 20,
    status: 'Active'
  },
    {
    id: 'p12',
    name: 'Fresh Basil',
    price: 800,
    unit: 'bunch',
    category: Category.HERBS,
    image: 'https://picsum.photos/id/500/600/600',
    vendorId: 'v1',
    description: 'Aromatic sweet basil.',
    rating: 4.8,
    reviews: 55,
    reviewsList: MOCK_REVIEWS,
    stock: 15,
    status: 'Active'
  },
];

export const CATEGORIES = [
  { name: Category.TUBERS, image: 'https://picsum.photos/id/111/300/300' },
  { name: Category.FRUITS, image: 'https://picsum.photos/id/1080/300/300' },
  { name: Category.VEGETABLES, image: 'https://picsum.photos/id/292/300/300' },
  { name: Category.MEAT, image: 'https://picsum.photos/id/300/300/300' },
  { name: Category.DAIRY, image: 'https://picsum.photos/id/108/300/300' },
  { name: Category.GRAINS, image: 'https://picsum.photos/id/75/300/300' },
  { name: Category.HERBS, image: 'https://picsum.photos/id/500/300/300' },
  { name: Category.NUTS, image: 'https://picsum.photos/id/305/300/300' },
  { name: Category.PANTRY, image: 'https://picsum.photos/id/312/300/300' },
];
